version: "3"
services:
  app:
    image: library/golang:1.15.8-alpine
    volumes:
      - .:/go/src/awesomeProject
    working_dir: /go/src/awesomeProject
    command: go run awesomeproject.go ratelimiter.go util.go
    ports:
      - "5000:5000"
    links:
      - redis
    environment:
      REDIS_URL: redis:6379
  redis:
    image: redis:alpine